const UserProfileStyle = {
    container: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: '100vh',
        backgroundColor: 'var(--color-page-bg)',
        fontFamily: 'var(--font-family)',
        margin: 0,
    },
    profileContainer: {
        position: 'relative',
    },
    topTrim: {
        width: '100%',
        height: 'var(--trim-height)',
        backgroundColor: 'var(--color-primary)',
        position: 'fixed',
        top: 0,
    },
    bottomTrim: {
        width: '100%',
        height: 'var(--trim-height)',
        backgroundColor: 'var(--color-primary)',
        position: 'fixed',
        bottom: 0,
    },
    profileBox: {
        width: '100%',
        maxWidth: '600px',
        backgroundColor: 'var(--color-card-bg)',
        padding: '40px',
        boxShadow: 'var(--shadow-card)',
        borderRadius: 'var(--radius-lg)',
        marginTop: '60px',
        marginBottom: '60px',
        boxSizing: 'border-box',
    },
    header: {
        fontSize: 'var(--font-size-3xl)',
        color: 'var(--color-text-primary)',
        marginBottom: '30px',
        textAlign: 'left',
    },
    profileCircle: {
        width: '50px',
        height: '50px',
        borderRadius: 'var(--radius-round)',
        backgroundColor: 'var(--color-primary)',
        color: 'white',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        fontSize: 'var(--font-size-3xl)',
        fontWeight: 'var(--font-weight-bold)',
        cursor: 'pointer',
    },
    navBar: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        paddingBottom: '15px',
        borderBottom: '1px solid var(--color-border-light)',
        marginBottom: '20px',
    },
    dropdownMenu: {
        position: 'absolute',
        top: '60px',
        right: '0',
        backgroundColor: 'var(--color-card-bg)',
        border: '1px solid var(--color-border)',
        boxShadow: 'var(--shadow-card)',
        borderRadius: 'var(--radius-sm)',
        width: '120px',
        zIndex: 100,
    },
    dropdownItem: {
        padding: '10px 15px',
        cursor: 'pointer',
        borderBottom: '1px solid var(--color-border-lighter)',
        color: 'var(--color-text-primary)',
    },
    menuLink: {
        color: 'var(--color-menu-link)',
        textDecoration: 'underline',
        fontSize: 'var(--font-size-xl)',
        cursor: 'pointer',
        marginBottom: '15px',
        display: 'block',
        textAlign: 'left',
        border: 'none',
        backgroundColor: 'transparent',
        padding: 0,
    },
    actionGroup: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        marginTop: '10px',
        marginBottom: '25px',
    },
    label: {
        fontSize: 'var(--font-size-lg)',
        color: 'var(--color-text-primary)',
        minWidth: '120px',
    },
    selectInput: {
        flex: 1,
        padding: '10px',
        backgroundColor: 'var(--color-input-bg)',
        color: 'var(--color-text-primary)',
        border: '1px solid var(--color-input-border)',
        borderRadius: 'var(--radius-sm)',
        fontSize: 'var(--font-size-lg)',
        cursor: 'pointer',
    },
    input: {
        flex: 1,
        padding: '12px',
        backgroundColor: 'var(--color-input-bg)',
        color: 'var(--color-text-primary)',
        border: '1px solid var(--color-input-border)',
        borderRadius: 'var(--radius-sm)',
        fontSize: 'var(--font-size-md)',
    },
    submitBtn: {
        padding: '10px 20px',
        backgroundColor: 'var(--color-primary)',
        color: '#ffffff',
        border: 'none',
        borderRadius: 'var(--radius-sm)',
        fontWeight: 'var(--font-weight-bold)',
        cursor: 'pointer',
        fontSize: 'var(--font-size-lg)',
    },
    backBtnStyle: {
        marginBottom: '20px',
        padding: '6px 14px',
        cursor: 'pointer',
        background: 'none',
        border: '1px solid var(--color-border-strong)',
        borderRadius: 'var(--radius-sm)',
        fontSize: 'var(--font-size-md)',
        color: 'var(--color-text-primary)',
    },
    searchDropdown: {
        position: 'absolute',
        top: '100%',
        left: 0,
        right: 0,
        backgroundColor: 'var(--color-card-bg)',
        border: '1px solid var(--color-border)',
        borderTop: 'none',
        boxShadow: 'var(--shadow-popup)',
        borderRadius: '0 0 var(--radius-sm) var(--radius-sm)',
        maxHeight: '200px',
        overflowY: 'auto',
        zIndex: 9999,
    },
    searchDropdownItem: {
        padding: '12px 15px',
        cursor: 'pointer',
        borderBottom: '1px solid var(--color-border-lighter)',
        color: 'var(--color-text-primary)',
        fontSize: 'var(--font-size-md)',
        backgroundColor: 'var(--color-card-bg)',
        textAlign: 'left',
    },
    createProjectInput: {
        width: '100%',
        padding: '12px',
        border: '1px solid var(--color-border)',
        borderRadius: 'var(--radius-sm)',
        marginBottom: '10px',
        boxSizing: 'border-box',
        backgroundColor: 'var(--color-input-bg)',
        color: 'var(--color-text-primary)',
    },

    //popup style

    modalOverlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'var(--color-overlay-light)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 2000,
    },
    modalContent: {
        backgroundColor: 'var(--color-card-bg)',
        padding: '30px',
        borderRadius: 'var(--radius-lg)',
        width: '90%',
        maxWidth: '500px',
        position: 'relative',
        maxHeight: '80vh',
        overflowY: 'auto',
        boxShadow: 'var(--shadow-popup-large)',
    },
    largeModalContent: {
        backgroundColor: 'var(--color-card-bg)',
        padding: '40px',
        borderRadius: 'var(--radius-lg)',
        width: '90%',
        maxWidth: '700px',
        position: 'relative',
        maxHeight: '85vh',
        overflowY: 'auto',
        boxShadow: 'var(--shadow-popup-large)',
    },
    closeModalBtn: {
        position: 'absolute',
        top: '15px',
        right: '15px',
        background: 'none',
        border: 'none',
        fontSize: 'var(--font-size-2xl)',
        fontWeight: 'var(--font-weight-bold)',
        cursor: 'pointer',
        color: 'var(--color-text-on-dark)',
    },
    pageHeading: {
        textAlign: 'center',
        textDecoration: 'underline',
    },
    table: {
        width: '100%',
        borderCollapse: 'collapse',
        marginTop: '10px',
    },
    th: {
        border: '1px solid var(--color-border)',
        padding: '10px',
        backgroundColor: 'var(--color-table-header-bg)',
        textAlign: 'center',
        fontWeight: 'var(--font-weight-bold)',
        color: 'var(--color-text-primary)',
    },
    td: {
        border: '1px solid var(--color-border)',
        padding: '10px',
        textAlign: 'center',
        color: 'var(--color-text-primary)',
    }

};

export default UserProfileStyle;
