const UserProfileStyle = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '100vh',
    backgroundColor: '#f4f7f9',
    fontFamily: 'Arial, sans-serif',
    margin: 0,
  },
  topTrim: {
    width: '100%',
    height: '40px',
    backgroundColor: '#c65c1a',
    position: 'fixed',
    top: 0,
  },
  bottomTrim: {
    width: '100%',
    height: '40px',
    backgroundColor: '#c65c1a',
    position: 'fixed',
    bottom: 0,
  },
  navBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    maxWidth: '600px',
    padding: '10px 20px',
    backgroundColor: '#fff',
    borderBottom: '1px solid #ddd',
    boxSizing: 'border-box',
  },
  profileBox: {
    width: '100%',
    maxWidth: '600px',
    backgroundColor: '#ffffff',
    padding: '40px',
    boxShadow: '0 4px 15px rgba(0,0,0,0.1)',
    borderRadius: '8px',
    marginTop: '60px',
    marginBottom: '60px',
    boxSizing: 'border-box',
  },
  header: {
    fontSize: '24px',
    color: '#333',
    marginBottom: '30px',
    textAlign: 'left',
  },
  profileIcon: {
    width: '45px',
    height: '45px',
    borderRadius: '50%',
    backgroundColor: '#c65c1a',
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '20px',
    fontWeight: 'bold',
    cursor: 'pointer',
    border: 'none',
  },
  menuLink: {
    color: '#6eb6ff',
    textDecoration: 'underline',
    fontSize: '18px',
    cursor: 'pointer',
    marginBottom: '15px',
    display: 'block',
    textAlign: 'left',
    border: 'none',
    backgroundColor: 'transparent',
    padding: 0,
  },
  actionGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginTop: '10px',
    marginBottom: '25px',
  },
  label: {
    fontSize: '16px',
    color: '#333',
  },
  input: {
    flex: 1,
    padding: '12px',
    backgroundColor: '#eed2c0',
    color: '#fff',
    border: 'none',
    borderRadius: '4px',
    fontSize: '14px',
  },
  submitBtn: {
    padding: '10px 20px',
    backgroundColor: '#c65c1a',
    color: '#000',
    border: 'none',
    borderRadius: '4px',
    fontWeight: 'bold',
    cursor: 'pointer',
    fontSize: '16px',
  },
  createProjectInput: {
    width: '100%',
    padding: '12px',
    border: '1px solid #333',
    borderRadius: '4px',
    marginBottom: '10px',
    boxSizing: 'border-box',
  }
};

export default UserProfileStyle;