const UserProfileStyle = {
    container: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: '100vh',
        backgroundColor: '#f4f7f9',
        fontFamily: 'Arial, sans-serif',
        margin: 0,
    },
    profileContainer: {
        position: 'relative',
    },
    topTrim: {
        width: '100%',
        height: '40px',
        backgroundColor: '#c65c1a',
        position: 'fixed',
        top: 0,
    },
    bottomTrim: {
        width: '100%',
        height: '40px',
        backgroundColor: '#c65c1a',
        position: 'fixed',
        bottom: 0,
    },
    profileBox: {
        width: '100%',
        maxWidth: '600px',
        backgroundColor: '#ffffff',
        padding: '40px',
        boxShadow: '0 4px 15px rgba(0,0,0,0.1)',
        borderRadius: '8px',
        marginTop: '60px',
        marginBottom: '60px',
        boxSizing: 'border-box',
    },
    header: {
        fontSize: '24px',
        color: '#333',
        marginBottom: '30px',
        textAlign: 'left',
    },
    profileCircle: {
        width: '50px',
        height: '50px',
        borderRadius: '50%',
        backgroundColor: '#c65c1a',
        color: 'white',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        fontSize: '24px',
        fontWeight: 'bold',
        cursor: 'pointer',
    },
    navBar: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        paddingBottom: '15px',
        borderBottom: '1px solid #ddd',
        marginBottom: '20px',
    },
    dropdownMenu: {
        position: 'absolute',
        top: '60px',
        right: '0',
        backgroundColor: '#fff',
        border: '1px solid #ccc',
        boxShadow: '0 4px 8px rgba(0,0,0,0.1)',
        borderRadius: '4px',
        width: '120px',
        zIndex: 100,
    },
    dropdownItem: {
        padding: '10px 15px',
        cursor: 'pointer',
        borderBottom: '1px solid #eee',
    },
    menuLink: {
        color: '#6eb6ff',
        textDecoration: 'underline',
        fontSize: '18px',
        cursor: 'pointer',
        marginBottom: '15px',
        display: 'block',
        textAlign: 'left',
        border: 'none',
        backgroundColor: 'transparent',
        padding: 0,
    },
    actionGroup: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        marginTop: '10px',
        marginBottom: '25px',
    },
    label: {
        fontSize: '16px',
        color: '#333',
        minWidth: '120px',
    },
    selectInput: {
        flex: 1,
        padding: '10px',
        backgroundColor: '#eed2c0',
        color: '#333',
        border: '1px solid #dcbfae',
        borderRadius: '4px',
        fontSize: '16px',
        cursor: 'pointer',
    },
    input: {
        flex: 1,
        padding: '12px',
        backgroundColor: '#eed2c0',
        color: '#fff',
        border: 'none',
        borderRadius: '4px',
        fontSize: '14px',
    },
    submitBtn: {
        padding: '10px 20px',
        backgroundColor: '#c65c1a',
        color: '#000',
        border: 'none',
        borderRadius: '4px',
        fontWeight: 'bold',
        cursor: 'pointer',
        fontSize: '16px',
    },
    backBtnStyle: {
        marginBottom: '20px',
        padding: '6px 14px',
        cursor: 'pointer',
        background: 'none',
        border: '1px solid #aaa',
        borderRadius: '4px',
        fontSize: '14px',
    },
    searchDropdown: {
        position: 'absolute',
        top: '100%',
        left: 0,
        right: 0,
        backgroundColor: '#fff',
        border: '1px solid #ccc',
        borderTop: 'none',
        boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
        borderRadius: '0 0 4px 4px',
        maxHeight: '200px',
        overflowY: 'auto',
        zIndex: 9999,
    },
    searchDropdownItem: {
        padding: '12px 15px',
        cursor: 'pointer',
        borderBottom: '1px solid #eee',
        color: '#333',
        fontSize: '14px',
        backgroundColor: '#fff',
        textAlign: 'left',
    },
    createProjectInput: {
        width: '100%',
        padding: '12px',
        border: '1px solid #333',
        borderRadius: '4px',
        marginBottom: '10px',
        boxSizing: 'border-box',
    },

    //popup style

    modalOverlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 2000,
    },
    modalContent: {
        backgroundColor: '#fff',
        padding: '30px',
        borderRadius: '8px',
        width: '90%',
        maxWidth: '500px',
        position: 'relative',
        maxHeight: '80vh',
        overflowY: 'auto',
        boxShadow: '0 4px 20px rgba(0,0,0,0.2)',
    },
    largeModalContent: {
        backgroundColor: '#fff',
        padding: '40px',
        borderRadius: '8px',
        width: '90%',
        maxWidth: '700px',
        position: 'relative',
        maxHeight: '85vh',
        overflowY: 'auto',
        boxShadow: '0 4px 20px rgba(0,0,0,0.2)',
    },
    closeModalBtn: {
        position: 'absolute',
        top: '15px',
        right: '15px',
        background: 'none',
        border: 'none',
        fontSize: '20px',
        fontWeight: 'bold',
        cursor: 'pointer',
        color: '#888',
    },
    pageHeading: {
        textAlign: 'center',
        textDecoration: 'underline',
    },
    table: {
        width: '100%',
        borderCollapse: 'collapse',
        marginTop: '10px',
    },
    th: {
        border: '1px solid #000',
        padding: '10px',
        backgroundColor: '#f9f9f9',
        textAlign: 'center',
        fontWeight: 'bold',
    },
    td: {
        border: '1px solid #000',
        padding: '10px',
        textAlign: 'center',
    }

};

export default UserProfileStyle;