export const AUTH_ACTIONS = {
    LOGIN: 'LOGIN',
    SIGNUP: 'SIGNUP',
    SIGNOUT: 'SIGNOUT',
    SIGNUP_REDIRECT: 'SIGNUP_REDIRECT',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    REQUEST_RESET: 'REQUEST_RESET',
    UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
    BACK_TO_LOGIN: 'BACK_TO_LOGIN'
};

export const APP_ROUTES = {
    LOGIN: '/login',
    SIGNUP: '/signup',
    PROFILE: '/profile',
    SIGNOUT: '/'
};